<?php

declare(strict_types=1);

return [
    [
        'id'                  => 1337,
        'name'                => 'منابع',
        'visible'             => 1,
        'summary'             => '',
        'summaryformat'       => 1,
        'section'             => 0,
        'hiddenbynumsections' => 0,
        'uservisible'         => true,
        'component'           => null,
        'itemid'              => null,
        'modules'             => [
            [
                'id'                  => 841,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=841',
                'name'                => 'آزمون تئوری WORD',
                'instance'            => 381,
                'contextid'           => 13998,
                'visible'             => 1,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 0,
                'downloadcontent'     => 1,
                'dates'               => [],
                'groupmode'           => 0,
            ],
            [
                'id'                  => 842,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=842',
                'name'                => 'آزمون تئوری EXCEL',
                'instance'            => 382,
                'contextid'           => 13999,
                'visible'             => 1,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 0,
                'downloadcontent'     => 1,
                'dates'               => [],
                'groupmode'           => 0,
            ],
            [
                'id'                  => 843,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=843',
                'name'                => 'آزمون تئوری PowerPoint',
                'instance'            => 383,
                'contextid'           => 14000,
                'visible'             => 1,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 0,
                'downloadcontent'     => 1,
                'dates'               => [],
                'groupmode'           => 0,
            ],
            [
                'id'                  => 844,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=844',
                'name'                => 'آزمون تئوری Access',
                'instance'            => 384,
                'contextid'           => 14001,
                'visible'             => 1,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 0,
                'downloadcontent'     => 1,
                'dates'               => [],
                'groupmode'           => 0,
            ],
            [
                'id'                  => 671,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=671',
                'name'                => 'آزمون ورد مقدماتی - عملی',
                'instance'            => 226,
                'contextid'           => 10062,
                'visible'             => 1,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 0,
                'downloadcontent'     => 1,
                'dates'               => [],
                'groupmode'           => 0,
            ],
            [
                'id'                  => 669,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=669',
                'name'                => 'آزمون اکسل مقدماتی - عملی',
                'instance'            => 224,
                'contextid'           => 10060,
                'visible'             => 1,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 0,
                'downloadcontent'     => 1,
                'dates'               => [],
                'groupmode'           => 0,
            ],
            [
                'id'                  => 673,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=673',
                'name'                => 'آزمون پاورپوینت مقدماتی - عملی',
                'instance'            => 228,
                'contextid'           => 10064,
                'visible'             => 1,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 0,
                'downloadcontent'     => 1,
                'dates'               => [],
                'groupmode'           => 0,
            ],
            [
                'id'                  => 672,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=672',
                'name'                => 'آزمون اکسس مقدماتی - عملی',
                'instance'            => 227,
                'contextid'           => 10063,
                'visible'             => 1,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 0,
                'downloadcontent'     => 1,
                'dates'               => [],
                'groupmode'           => 0,
            ],
            [
                'id'                  => 604,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=604',
                'name'                => 'آزمون ورد مقدماتی - تئوری',
                'instance'            => 184,
                'contextid'           => 8436,
                'visible'             => 0,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 1,
                'completiondata'      => [
                    'state'             => 0,
                    'timecompleted'     => 0,
                    'overrideby'        => null,
                    'valueused'         => false,
                    'hascompletion'     => true,
                    'isautomatic'       => false,
                    'istrackeduser'     => false,
                    'uservisible'       => true,
                    'details'           => [],
                    'isoverallcomplete' => false,
                ],
                'downloadcontent' => 1,
                'dates'           => [],
                'groupmode'       => 0,
            ],
            [
                'id'                  => 603,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=603',
                'name'                => 'آزمون اکسل مقدماتی - تئوری',
                'instance'            => 183,
                'contextid'           => 8435,
                'visible'             => 0,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 1,
                'completiondata'      => [
                    'state'             => 0,
                    'timecompleted'     => 0,
                    'overrideby'        => null,
                    'valueused'         => false,
                    'hascompletion'     => true,
                    'isautomatic'       => false,
                    'istrackeduser'     => false,
                    'uservisible'       => true,
                    'details'           => [],
                    'isoverallcomplete' => false,
                ],
                'downloadcontent' => 1,
                'dates'           => [],
                'groupmode'       => 0,
            ],
            [
                'id'                  => 605,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=605',
                'name'                => 'آزمون پاورپوینت مقدماتی - تئوری',
                'instance'            => 185,
                'contextid'           => 8437,
                'visible'             => 0,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 1,
                'completiondata'      => [
                    'state'             => 0,
                    'timecompleted'     => 0,
                    'overrideby'        => null,
                    'valueused'         => false,
                    'hascompletion'     => true,
                    'isautomatic'       => false,
                    'istrackeduser'     => false,
                    'uservisible'       => true,
                    'details'           => [],
                    'isoverallcomplete' => false,
                ],
                'downloadcontent' => 1,
                'dates'           => [],
                'groupmode'       => 0,
            ],
            [
                'id'                  => 612,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=612',
                'name'                => 'آزمون اکسس مقدماتی - تئوری',
                'instance'            => 187,
                'contextid'           => 8497,
                'visible'             => 0,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 1,
                'completiondata'      => [
                    'state'             => 0,
                    'timecompleted'     => 0,
                    'overrideby'        => null,
                    'valueused'         => false,
                    'hascompletion'     => true,
                    'isautomatic'       => false,
                    'istrackeduser'     => false,
                    'uservisible'       => true,
                    'details'           => [],
                    'isoverallcomplete' => false,
                ],
                'downloadcontent' => 1,
                'dates'           => [],
                'groupmode'       => 0,
            ],
            [
                'id'                  => 614,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=614',
                'name'                => 'آزمون عملی ورد مقدماتی',
                'instance'            => 189,
                'contextid'           => 8499,
                'visible'             => 0,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 1,
                'completiondata'      => [
                    'state'             => 0,
                    'timecompleted'     => 0,
                    'overrideby'        => null,
                    'valueused'         => false,
                    'hascompletion'     => true,
                    'isautomatic'       => false,
                    'istrackeduser'     => false,
                    'uservisible'       => true,
                    'details'           => [],
                    'isoverallcomplete' => false,
                ],
                'downloadcontent' => 1,
                'dates'           => [],
                'groupmode'       => 0,
            ],
            [
                'id'                  => 616,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=616',
                'name'                => 'آزمون عملی نرم افزار پاور پوینت',
                'instance'            => 191,
                'contextid'           => 8501,
                'visible'             => 0,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 1,
                'completiondata'      => [
                    'state'             => 0,
                    'timecompleted'     => 0,
                    'overrideby'        => null,
                    'valueused'         => false,
                    'hascompletion'     => true,
                    'isautomatic'       => false,
                    'istrackeduser'     => false,
                    'uservisible'       => true,
                    'details'           => [],
                    'isoverallcomplete' => false,
                ],
                'downloadcontent' => 1,
                'dates'           => [],
                'groupmode'       => 0,
            ],
            [
                'id'                  => 615,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=615',
                'name'                => 'آزمون نرم افزار اکسل - عملی',
                'instance'            => 190,
                'contextid'           => 8500,
                'visible'             => 0,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 1,
                'completiondata'      => [
                    'state'             => 0,
                    'timecompleted'     => 0,
                    'overrideby'        => null,
                    'valueused'         => false,
                    'hascompletion'     => true,
                    'isautomatic'       => false,
                    'istrackeduser'     => false,
                    'uservisible'       => true,
                    'details'           => [],
                    'isoverallcomplete' => false,
                ],
                'downloadcontent' => 1,
                'dates'           => [],
                'groupmode'       => 0,
            ],
            [
                'id'                  => 617,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=617',
                'name'                => 'آزمون عملی نرم افزار اکسس',
                'instance'            => 192,
                'contextid'           => 8502,
                'visible'             => 0,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 1,
                'completiondata'      => [
                    'state'             => 0,
                    'timecompleted'     => 0,
                    'overrideby'        => null,
                    'valueused'         => false,
                    'hascompletion'     => true,
                    'isautomatic'       => false,
                    'istrackeduser'     => false,
                    'uservisible'       => true,
                    'details'           => [],
                    'isoverallcomplete' => false,
                ],
                'downloadcontent' => 1,
                'dates'           => [],
                'groupmode'       => 0,
            ],
            [
                'id'                  => 1072,
                'url'                 => 'https://lms.jedu.ir/mod/qbank/view.php?id=1072',
                'name'                => 'ICDL مجازی shared question bank',
                'instance'            => 113,
                'contextid'           => 14905,
                'description'         => '<div class="no-overflow">This question bank was created automatically when the site was upgraded.</div>',
                'visible'             => 0,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/qbank/1777806723/monologo?filtericon=1',
                'modname'             => 'qbank',
                'purpose'             => 'content',
                'branded'             => false,
                'modplural'           => 'بانک سؤالات',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => false,
                'completion'          => 0,
                'downloadcontent'     => 1,
                'dates'               => [],
                'groupmode'           => 0,
            ],
            [
                'id'                  => 1152,
                'url'                 => 'https://lms.jedu.ir/mod/quiz/view.php?id=1152',
                'name'                => 'dsff',
                'instance'            => 509,
                'contextid'           => 15427,
                'visible'             => 1,
                'uservisible'         => true,
                'visibleoncoursepage' => 1,
                'modicon'             => 'https://lms.jedu.ir/theme/image.php/mb2nl/quiz/1777806723/monologo?filtericon=1',
                'modname'             => 'quiz',
                'purpose'             => 'assessment',
                'branded'             => false,
                'modplural'           => 'آزمون‌ها',
                'availability'        => null,
                'indent'              => 0,
                'onclick'             => '',
                'afterlink'           => null,
                'customdata'          => '""',
                'noviewlink'          => false,
                'candisplay'          => true,
                'completion'          => 0,
                'downloadcontent'     => 1,
                'dates'               => [],
                'groupmode'           => 0,
            ],
        ],
    ],
];
