sonar.projectKey=laravel-audit
sonar.projectName=Laravel Audit
sonar.sources=app
sonar.exclusions=**/app/Providers/**, **/vendor/**, **/node_modules/**, **/docker/**, **/lang/**, **/bootstrap/**, **/config/*, **/storage/**, **/public/**, **/tests/**
sonar.language=php
sonar.inclusions=**/*.php,**/*.js,**/*.ts,**/*.vue,**/*.blade.php,**/*.css,**/*.json
sonar.sourceEncoding=UTF-8
