<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * Defines application permissions.
 * Generated by: php artisan permissions:generate-enum
 *
 * DO NOT EDIT MANUALLY - Re-run the command to update.
 */
enum PermissionEnum: string
{
    case ADVICE_REQUEST_CREATE            = 'advice_request.create';
    case ADVICE_REQUEST_DELETE            = 'advice_request.delete';
    case ADVICE_REQUEST_UPDATE            = 'advice_request.update';
    case ADVICE_REQUEST_VIEW              = 'advice_request.view';
    case ADVICE_REQUEST_VIEW_ANY          = 'advice_request.view_any';
    case AUDIT_ADMIN_ACTIONS_VIEW         = 'audit.admin_actions_view';
    case AUDIT_COMPLIANCE_REPORTS_VIEW    = 'audit.compliance_reports_view';
    case AUDIT_SUSPICIOUS_ACTIVITY_VIEW   = 'audit.suspicious_activity_view';
    case BLOG_CATEGORY_CREATE             = 'blog_category.create';
    case BLOG_CATEGORY_DELETE             = 'blog_category.delete';
    case BLOG_CATEGORY_UPDATE             = 'blog_category.update';
    case BLOG_CATEGORY_VIEW               = 'blog_category.view';
    case BLOG_CATEGORY_VIEW_ANY           = 'blog_category.view_any';
    case BLOG_POST_CREATE                 = 'blog_post.create';
    case BLOG_POST_DELETE                 = 'blog_post.delete';
    case BLOG_POST_FEATURE                = 'blog_post.feature';
    case BLOG_POST_PUBLISH                = 'blog_post.publish';
    case BLOG_POST_UPDATE                 = 'blog_post.update';
    case BLOG_POST_VIEW                   = 'blog_post.view';
    case BLOG_POST_VIEW_ANY               = 'blog_post.view_any';
    case CATEGORY_CREATE                  = 'category.create';
    case CATEGORY_DELETE                  = 'category.delete';
    case CATEGORY_DELETE_OWN              = 'category.delete_own';
    case CATEGORY_UPDATE                  = 'category.update';
    case CATEGORY_UPDATE_OWN              = 'category.update_own';
    case CATEGORY_VIEW                    = 'category.view';
    case CATEGORY_VIEW_ANY                = 'category.view_any';
    case COURSE_CREATE                    = 'course.create';
    case COURSE_DELETE                    = 'course.delete';
    case COURSE_DELETE_OWN                = 'course.delete_own';
    case COURSE_UPDATE                    = 'course.update';
    case COURSE_UPDATE_OWN                = 'course.update_own';
    case COURSE_VIEW                      = 'course.view';
    case COURSE_VIEW_ANY                  = 'course.view_any';
    case DISCOUNT_CREATE                  = 'discount.create';
    case DISCOUNT_DELETE                  = 'discount.delete';
    case DISCOUNT_UPDATE                  = 'discount.update';
    case DISCOUNT_VIEW                    = 'discount.view';
    case DISCOUNT_VIEW_ANY                = 'discount.view_any';
    case ENROLLMENT_CREATE                = 'enrollment.create';
    case ENROLLMENT_DELETE                = 'enrollment.delete';
    case ENROLLMENT_UPDATE                = 'enrollment.update';
    case ENROLLMENT_VIEW                  = 'enrollment.view';
    case ENROLLMENT_VIEW_ANY              = 'enrollment.view_any';
    case FILE_CREATE                      = 'file.create';
    case FILE_DELETE                      = 'file.delete';
    case FILE_DELETE_OWN                  = 'file.delete_own';
    case FILE_UPDATE                      = 'file.update';
    case FILE_UPDATE_OWN                  = 'file.update_own';
    case FILE_VIEW                        = 'file.view';
    case FILE_VIEW_ANY                    = 'file.view_any';
    case HOME_PAGE_BLOCK_CREATE           = 'home_page_block.create';
    case HOME_PAGE_BLOCK_DELETE           = 'home_page_block.delete';
    case HOME_PAGE_BLOCK_UPDATE           = 'home_page_block.update';
    case HOME_PAGE_BLOCK_VIEW             = 'home_page_block.view';
    case HOME_PAGE_BLOCK_VIEW_ANY         = 'home_page_block.view_any';
    case ORDER_APPROVE                    = 'order.approve';
    case ORDER_CREATE                     = 'order.create';
    case ORDER_DELETE                     = 'order.delete';
    case ORDER_UPDATE                     = 'order.update';
    case ORDER_VIEW                       = 'order.view';
    case ORDER_VIEW_ANY                   = 'order.view_any';
    case PARTNER_CREATE                   = 'partner.create';
    case PARTNER_DELETE                   = 'partner.delete';
    case PARTNER_UPDATE                   = 'partner.update';
    case PARTNER_VIEW                     = 'partner.view';
    case PARTNER_VIEW_ANY                 = 'partner.view_any';
    case PAYMENT_CREATE                   = 'payment.create';
    case PAYMENT_DELETE                   = 'payment.delete';
    case PAYMENT_UPDATE                   = 'payment.update';
    case PAYMENT_VIEW                     = 'payment.view';
    case PAYMENT_VIEW_ANY                 = 'payment.view_any';
    case PRODUCT_CREATE                   = 'product.create';
    case PRODUCT_DELETE                   = 'product.delete';
    case PRODUCT_DELIVERY_OPTION_CREATE   = 'product_delivery_option.create';
    case PRODUCT_DELIVERY_OPTION_DELETE   = 'product_delivery_option.delete';
    case PRODUCT_DELIVERY_OPTION_UPDATE   = 'product_delivery_option.update';
    case PRODUCT_DELIVERY_OPTION_VIEW     = 'product_delivery_option.view';
    case PRODUCT_DELIVERY_OPTION_VIEW_ANY = 'product_delivery_option.view_any';
    case PRODUCT_UPDATE                   = 'product.update';
    case PRODUCT_VIEW                     = 'product.view';
    case PRODUCT_VIEW_ANY                 = 'product.view_any';
    case REFUND_CREATE                    = 'refund.create';
    case REFUND_DELETE                    = 'refund.delete';
    case REFUND_UPDATE                    = 'refund.update';
    case REFUND_UPDATE_STATUS             = 'refund.update_status';
    case REFUND_VIEW                      = 'refund.view';
    case REFUND_VIEW_ANY                  = 'refund.view_any';
    case REVIEW_DELETE                    = 'review.delete';
    case REVIEW_UPDATE                    = 'review.update';
    case REVIEW_UPDATE_FEATURED_STATUS    = 'review.update_featured_status';
    case REVIEW_VIEW                      = 'review.view';
    case REVIEW_VIEW_ANY                  = 'review.view_any';
    case ROLE_CREATE                      = 'role.create';
    case ROLE_DELETE                      = 'role.delete';
    case ROLE_UPDATE                      = 'role.update';
    case ROLE_VIEW                        = 'role.view';
    case ROLE_VIEW_ANY                    = 'role.view_any';
    case SEMINAR_CREATE                   = 'seminar.create';
    case SEMINAR_DELETE                   = 'seminar.delete';
    case SEMINAR_DELETE_OWN               = 'seminar.delete_own';
    case SEMINAR_UPDATE                   = 'seminar.update';
    case SEMINAR_UPDATE_OWN               = 'seminar.update_own';
    case SEMINAR_VIEW                     = 'seminar.view';
    case SEMINAR_VIEW_ANY                 = 'seminar.view_any';
    case SETTING_UPDATE                   = 'setting.update';
    case SETTING_VIEW_ANY                 = 'setting.view_any';
    case SLIDER_CREATE                    = 'slider.create';
    case SLIDER_DELETE                    = 'slider.delete';
    case SLIDER_UPDATE                    = 'slider.update';
    case SLIDER_VIEW                      = 'slider.view';
    case SLIDER_VIEW_ANY                  = 'slider.view_any';
    case STAFF_CREATE                     = 'staff.create';
    case STAFF_DELETE                     = 'staff.delete';
    case STAFF_IMPERSONATE                = 'staff.impersonate';
    case STAFF_MANAGE_ROLES               = 'staff.manage_roles';
    case STAFF_UPDATE                     = 'staff.update';
    case STAFF_VIEW                       = 'staff.view';
    case STAFF_VIEW_ANY                   = 'staff.view_any';
    case STUDENT_STORY_CREATE             = 'student_story.create';
    case STUDENT_STORY_DELETE             = 'student_story.delete';
    case STUDENT_STORY_UPDATE             = 'student_story.update';
    case STUDENT_STORY_VIEW               = 'student_story.view';
    case STUDENT_STORY_VIEW_ANY           = 'student_story.view_any';
    case TEACHER_CREATE                   = 'teacher.create';
    case TEACHER_DELETE                   = 'teacher.delete';
    case TEACHER_UPDATE                   = 'teacher.update';
    case TEACHER_VIEW                     = 'teacher.view';
    case TEACHER_VIEW_ANY                 = 'teacher.view_any';
    case TERM_CREATE                      = 'term.create';
    case TERM_DELETE                      = 'term.delete';
    case TERM_UPDATE                      = 'term.update';
    case TERM_VIEW                        = 'term.view';
    case TERM_VIEW_ANY                    = 'term.view_any';
    case USER_CREATE                      = 'user.create';
    case USER_DELETE                      = 'user.delete';
    case USER_UPDATE                      = 'user.update';
    case USER_VIEW                        = 'user.view';
    case USER_VIEW_ANY                    = 'user.view_any';
    case VENDOR_CREATE                    = 'vendor.create';
    case VENDOR_DELETE                    = 'vendor.delete';
    case VENDOR_UPDATE                    = 'vendor.update';
    case VENDOR_VIEW                      = 'vendor.view';
    case VENDOR_VIEW_ANY                  = 'vendor.view_any';
    case WALLET_ADJUSTMENT                = 'wallet.adjustment';
    case WALLET_CAMPAIGN_ALLOCATE         = 'wallet_campaign.allocate';
    case WALLET_CAMPAIGN_CREATE           = 'wallet_campaign.create';
    case WALLET_CAMPAIGN_DELETE           = 'wallet_campaign.delete';
    case WALLET_CAMPAIGN_PROCESS_BONUS    = 'wallet_campaign.process_bonus';
    case WALLET_CAMPAIGN_UPDATE           = 'wallet_campaign.update';
    case WALLET_CAMPAIGN_VIEW             = 'wallet_campaign.view';
    case WALLET_CAMPAIGN_VIEW_ANY         = 'wallet_campaign.view_any';
    case WALLET_CREATE                    = 'wallet.create';
    case WALLET_DELETE                    = 'wallet.delete';
    case WALLET_DEPOSIT                   = 'wallet.deposit';
    case WALLET_UPDATE                    = 'wallet.update';
    case WALLET_VIEW                      = 'wallet.view';
    case WALLET_VIEW_ANY                  = 'wallet.view_any';
    case WALLET_WITHDRAWAL                = 'wallet.withdrawal';

    /**
     * Get all permission values as an array.
     *
     * @return array<string>
     */
    public static function getAllValues(): array
    {
        return array_column(self::cases(), 'value');
    }

    /**
     * Get all permission names (enum case names) as an array.
     *
     * @return array<string>
     */
    public static function getAllNames(): array
    {
        return array_column(self::cases(), 'name');
    }
}
