<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * Defines application permissions.
 * Generated by: php artisan permissions:generate-enum
 *
 * DO NOT EDIT MANUALLY - Re-run the command to update.
 */
enum PermissionEnum: string
{
    case CATEGORY_CREATE = 'categories.create';
    case CATEGORY_DELETE = 'categories.delete';
    case CATEGORY_DELETE_OWN = 'categories.delete_own';
    case CATEGORY_UPDATE = 'categories.update';
    case CATEGORY_UPDATE_OWN = 'categories.update_own';
    case CATEGORY_VIEW = 'categories.view';
    case CATEGORY_VIEW_ANY = 'categories.view_any';
    case COURSE_CREATE = 'courses.create';
    case COURSE_DELETE = 'courses.delete';
    case COURSE_DELETE_OWN = 'courses.delete_own';
    case COURSE_UPDATE = 'courses.update';
    case COURSE_UPDATE_OWN = 'courses.update_own';
    case COURSE_VIEW = 'courses.view';
    case COURSE_VIEW_ANY = 'courses.view_any';

    /**
     * Get all permission values as an array.
     *
     * @return array<string>
     */
    public static function getAllValues(): array
    {
        return array_column(self::cases(), 'value');
    }

    /**
     * Get all permission names (enum case names) as an array.
     *
     * @return array<string>
     */
    public static function getAllNames(): array
    {
        return array_column(self::cases(), 'name');
    }
}
